### ISSUE TITLE
Missing versions (2.x.x) on maven

### ISSUE THREAD

**Issue by maroshmka** [Colisweb/scala-opentracing#11]
hello, 

i can see only 3.1.0 version on maven.

https://repo1.maven.org/maven2/com/colisweb/scala-opentracing-context_2.12/

Is this expected? we've been using 2.5.0 in our repo, now we can't download it.

**Comment by maroshmka** [comment]
also, bintray is returning 404 - https://bintray.com/colisweb/maven/scala-opentracing-context 

and on this 403 - https://dl.bintray.com/colisweb/maven/com/colisweb/scala-opentracing-http4s-client-blaze_2.12/2.5.0/scala-opentracing-http4s-client-blaze_2.12-2.5.0.pom

**Comment by LitlBro** [comment]
Hi, bintray does not longer exists (see (sunsetting)[https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/].
As for the fist question, it is intended. We encourage you to upgrade to the latest version 3.1.0, as 2.5.0 was released last August

**Comment by maroshmka** [comment]
rip us, we have a legacy service that uses the 2.5.x version. but anyway, thanks
