### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by endertunc** [Colisweb/scala-opentracing#5]
Current README seems to be outdated. I had to spent half an hour to actually figure out how to compile http4s example (You can see the updated example in https://github.com/Colisweb/scala-opentracing/pull/4). It looks like that there was a quite a lot refactoring and moving thing around (no more `scala-opentracing` ) and even new packages (`scala-opentracing-core`) but none of those thing actually mentioned anywhere. 

I would suggest to:
- List available packages, add latest version badges and describe their usage so user doesn't have to dig https://bintray.com/colisweb/maven
- Revisit example codes and fix the ones that are broken

**Comment by LitlBro** [comment]
Hi and thanks for the issue + PR

The team moved our main projects to gitlab, they are being developed here now (we should mention that somewhere...).

https://gitlab.com/colisweb-open-source/scala/scala-opentracing/

Doc is already subject to a PR and being reviewed.

**Comment by endertunc** [comment]
@LitlBro thanks for the clarifications. I would suggest to use this issue to mention the fact that development moved to Gitlab or even maybe archive this repo.

**Comment by LitlBro** [comment]
Hi @endertunc ,
I will close the issue, the Readme has been updated, tell us if there is something else needed to be changed there :)

After talking with our team I think we won't archive this repo, mainly for visibility reason.
Most people that find this project seem to find it through Github.
