### ISSUE TITLE
Question: Context Propagation

### ISSUE THREAD

**Issue by timbess** [Colisweb/scala-opentracing#7]
I've been testing out this library with datadog but I can't get the traces between client and server to relate at all in datadog's UI. I was able to view the spans individually by tagging them all with a unique id, but I don't see how this correlates the traces without passing on the trace id, etc. like b3-propagation does. Any thoughts?

**Comment by LitlBro** [comment]
If I am not mistaken you are referring to distributed tracing, this is explained in the possible improvements at the [end of our docs](https://github.com/Colisweb/scala-opentracing#contributing):
```
Right now this library does not support distributed tracing,   
i.e the ability to continue a serialized trace from another application and/or send an unfinished trace to another application.
```

On another note, you should not have to tag spans with a unique id, the library should do that for you. Do you have some code snippet to share ?

**Comment by timbess** [comment]
Ah I see, must have missed that part in the docs. I ended up implementing something similar to [natchez](https://github.com/tpolecat/natchez) internally at work so we could use the distributed tracing. It may have tagged them with unique ids, I just meant that I was tagging them with my own ids as well.

**Comment by LitlBro** [comment]
Ok, I will close this issue then. I will let you know when distributed tracing is available if you are interested !
